language: ruby

cache: bundler

rvm:
  - 2.6.1

services: postgresql

before_script:
  - psql -c 'create database daysinturkey_test;' -U postgres
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rake

notifications:
  email: false

deploy:
  provider: heroku
  api_key:
    secure: PdqFvJPGsDxNbw9sNUbIVqHpPr/isaoFwGeJBbxYW0cPCpyREpzonpVbt30mEr9XWyidaodE7VyZ+LvVy0gpyPEYerXKpZOzgk62A6RkGtYYvWGysERB7GHCpXGACxrOgIhrC/fdCBG66BPnYMUz6K/6JMzDTLtXgYeTizItsF4=
  app: daysinturkey-production
  on:
    repo: NoryDev/visacountdown
  run:
    - "rake db:migrate"
    - restart
