language: ruby

cache: bundler

rvm:
  - 2.6.5

services: postgresql

before_script:
  - psql -c 'create database daysinturkey_test;' -U postgres
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rake

notifications:
  email: false

deploy:
  provider: heroku
  api_key:
    secure: jqCvM5pbJXZcuP3ZOhdcI9f3KtUpJ2nS+d26A9zeT5sRuQA1ftpOQdbNdvpGEOEQAp2KP5I8iW8bi40wXoZCjJ/KLLnISwmBjbu20h9YMwXHt4V4I5f9fvaLDtAGi3k7lFL1KgatHEyTElRimpsK84RXsGxMGOwm3lRw5mJFZjs=
  app: daysinturkey-production
  on:
    repo: NoryDev/visacountdown
  run:
    - "rake db:migrate"
    - restart
