language: ruby

rvm:
  - 2.2.0

services: postgresql

before_script:
  - psql -c 'create database visacountdown_test;' -U postgres
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rake